---
title: "Case Study 1"
author: "Yucheol Shin"
date: "6/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Prepare Data
```{r}
library(ggplot2)
library(tidyr)
#library(plotly)
library(dplyr)
beers = read.csv("C:/Users/User 1/Desktop/SMU/DS6306/CaseStudy1/Beers.csv", header = TRUE)
breweries = read.csv("C:/Users/User 1/Desktop/SMU/DS6306/CaseStudy1/Breweries.csv", header = TRUE)
```

# Number of Breweries per state
```{r}
totalState = count(breweries, State)
breweries %>% ggplot(aes(x=State, fill = State)) + geom_bar() + geom_text(aes(State, n + 1, label=n, fill = NULL), data= totalState) + ggtitle("Number of Breweries for each State")
```

# Merge two data
```{r}
colnames(beers)[5] = "Brew_ID"
fullData = merge(beers, breweries, by = "Brew_ID")
head(fullData)
```

# Missing values
```{r}
sapply(fullData, function(x) sum(is.na(x)))

cleanData = fullData %>% filter(!is.na(ABV) & !is.na(IBU))
```

# Median ABV and IBU per states
```{r}
cleanData %>% group_by(State) %>% summarize(medianABV = median(ABV), medianIBU = median(IBU), count = n())

cleanData %>% 
  group_by(State) %>% 
  summarise(medianABV = median(ABV)) %>% 
  gather(key, value, -State) %>% 
  ggplot(aes(State, value, fill = key)) + geom_bar(stat = "identity", position = "dodge") + ggtitle("Median ABV for each State")

cleanData %>% 
  group_by(State) %>% 
  summarise(medianIBU = median(IBU)) %>% 
  gather(key, value, -State) %>% 
  ggplot(aes(State, value, fill = key)) + geom_bar(stat = "identity", position = "dodge") + ggtitle("Median IBU for each State") 

```


# Max ABV and IBU of state
# Which state has max ABV / IBU
```{r}
cleanData %>% group_by(State) %>% summarize(maxABV = max(ABV), maxIBU = max(IBU))

maxABV = max(cleanData$ABV)
maxIBU = max(cleanData$IBU)

cleanData %>% filter(ABV == maxABV)
cleanData %>% filter(IBU == maxIBU)

```




# Summarize ABV
```{r}
summary(cleanData$ABV)

# Histogram of ABV Percentage 
cleanData  %>% ggplot(aes(ABV*100)) + geom_histogram(fill="darkblue",color="black", binwidth= 0.375) + xlab("% Alcohol by Volume (%ABV)") + ggtitle("Distribution of Beer %ABV, Right-Skewed") 

# Box Plot
boxplot(cleanData$ABV, col='orange',main = 'Alcohol by volume')

# QQ plot for normality check
qqnorm(cleanData$ABV, pch = 1, frame = FALSE)
qqline(cleanData$ABV, col = "steelblue", lwd = 2, main = 'Alcohol by volume')

```

# Relationship between ABV and IBU
```{r}
# Scatter Plot for ABV vs IBU for each State
cleanData %>% ggplot(aes(x=IBU, y=ABV, color=State)) + geom_point()

#7 Scatter Plot for ABV vs IBU relationship
theme_set(theme_bw())  # pre-set the bw theme.
g <- ggplot(cleanData, aes(IBU, ABV, color='red'))
g + geom_point(color='blue') + 
  geom_smooth(method="lm", se=F) +
  labs(y="ABV", 
       x="IBU", 
       title="ABV vs IBU Relationship")

```



# KNN
```{r}
filterData = cleanData %>% filter(grepl("Ale", Style) | grepl("IPA", Style))
```
